### ISSUE TITLE
Async task state tracking

### ISSUE THREAD

**Issue by nathanielrindlaub** [tnc-ca-geo/animl-api#148]
We now have a growing number of potentially long-running tasks that Lambdas are not well suited to support, especially if the user is expecting a synchronous response. These include:

- [x] Bulk upload
- [ ] [Deleting large numbers of images](https://github.com/tnc-ca-geo/animl-frontend/issues/227)
- [ ] Deleting large numbers of labels (high priority, very expensive & hard to optimize with `bulkWrite`)
- [ ] Merging large numbers of labels
- [ ] Creating large numbers of labels
- [ ] [Updating camera serial numbers](https://github.com/tnc-ca-geo/animl-frontend/issues/228)
- [x] Getting View stats
- [x] Exporting annotations
- [x] Updating deployments

@ingalls recommends that we consider creating a consistent pattern for tracking these async tasks in the DB (creating a collection or collections that we update when the state of one of these processes changes and a consistent query pattern for accessing them). I think it's a great idea... right now we have 2 entirely different ways of checking the bulk upload state and the annotation state, and for most of the others we haven't yet implemented spinning the tasks off on separate infrastructure; instead, we only support them at pretty low thresholds. 

For the tasks we haven't yet broken out to run async, we have a couple options:
1. Using AWS Batch (same process as batch upload) w/ Fargate. This would be more expensive and have a much longer cold-start, but it would mean that we wouldn’t be limited to Lambda’s 15 min limit
2. Create SQSs + Lambda workers to pull messages off and process them in separate Lambdas. Nick's main concern here is how do we make the UX make sense for tasks that run longer than 15 mins (and would require re-prompting/initiating by the user)

**Comment by postfalk** [comment]
I think that is a good idea. I have a similar design with my Lens to Salesforce workflow.

Falk



Falk Schuetzenmeister

Engineering Lead

The Nature Conservancy in California
***@***.***

(510) 604-8010


[cid:2ed45c50-8c24-4344-a0cf-581e1a0a6237]<https://www.nature.org/en-us/about-us/where-we-work/united-states/california/?vu=california>





















________________________________
From: Natty Rindlaub ***@***.***>
Sent: Monday, February 12, 2024 1:22 PM
To: tnc-ca-geo/animl-api ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [tnc-ca-geo/animl-api] Async task state tracking (Issue #148)


We now have a growing number of potentially long-running tasks that Lambdas are not well suited to support, especially if the user is expecting a synchronous response. These include:

  *   Bulk upload
  *   Deleting large numbers of images
  *   Deleting large numbers of labels
  *   Merging large numbers of labels
  *   Getting View stats
  *   Exporting annotations

@ingalls<https://github.com/ingalls> recommends that we consider creating a consistent pattern for tracking these async tasks in the DB (creating a collection or collections that we update when the state of one of these processes changes and a consistent query pattern for accessing them). I think it's a great idea... right now we have 2 entirely different ways of checking the bulk upload state and the annotation state, and for most of the others we haven't yet implemented spinning the tasks off on separate infrastructure; instead, we only support them at pretty low thresholds.

For the tasks we haven't yet broken out to run async, we have a couple options:

  1.  Using AWS Batch (same process as batch upload) w/ Fargate. This would be more expensive and have a much longer cold-start, but it would mean that we wouldn’t be limited to Lambda’s 15 min limit
  2.  Create SQSs + Lambda workers to pull messages off and process them in separate Lambdas. Nick's main concern here is how do we make the UX make sense for tasks that run longer than 15 mins (and would require re-prompting/initiating by the user)

**Comment by nathanielrindlaub** [comment]
@ingalls, I was just made aware that the process of creating, updating, or deleting deployments on cameras with large numbers of images (like 20k) will timeout, and the deployment update will fail. This is because `ProjectModel.reMapImagesToDeps()` has to iterate over every image in the camera to make sure it's assigned to the right deployment. 

So once we get the task tracking in place I think our two priorities should be:
1. making `getStats` async
2. making `reMapImagesToDeps` (or all deployment CRUD ops) async

**Comment by nathanielrindlaub** [comment]
I think this is just about done. We've migrated `getStats`, `exportData`, `exportImageErrors`,  and`create/update/deleteDeployments` to the new async task lambda. We decided against using the task pattern for `batches` as they are much more involved and deeply integrated in the rest of the code base. It's worth, however, looking at whether we can now move some of the other time-bound operations (Deleting large numbers of images, Deleting large numbers of labels, Merging large numbers of labels) to async and increasing or removing the allowable threshold. 

Final punchlist:
- [ ] review access patterns / interfaces between new task handler the various DB Models they interface with. Right now there's some inconsistency and semi-confusing function names (see: https://github.com/tnc-ca-geo/animl-api/pull/168#discussion_r1542059424)
- [ ] review frontend task slice and see if there are any opportunities to streamline or abstract it. At the very least, generalize `getTaskFailure` action handler so it works for all task types.

**Comment by nathanielrindlaub** [comment]
Capturing some ideas discussed in our software team meeting last week (11/26):

Approaches to handling long running tasks:

- **Look for opportunities to maximize the use bulk MongoDB CRUD ops like `bulkWrite()` and `updateMany()`**. Situations in which we have to iterate over individual records before updating them - for example if we need to inspect certain document properties in order to determine how we'll need to update them, e.g. like we do [when deleting labels from images](https://github.com/tnc-ca-geo/animl-api/blob/ac4d21046929c128a4836fceebf700c2444efced/src/api/db/models/Image.ts#L956C1-L970C6)) - is the worst-case scenario. There are, however, often creative ways to squeeze some juice out of challenging situations like that. For example, @jue-henry was able to [make image deletion 15x faster](https://github.com/tnc-ca-geo/animl-api/pull/278) by performing bulk S3 object deletion requests and grouping the MongoDB deletion calls into batches of 300 images at a time.

- **Make operations more efficient by creating high-level, meta-properties in documents that represent certain states rather than having to inspect and infer complex states from deeply nested sub-documents.** A good example of this is @jue-henry's implementation of the the [`Image.reviewed`](https://github.com/tnc-ca-geo/animl-api/pull/172) property.

- **Set flag, perform scheduled clean-up in the background**. For example, a much better approach for deleting images rather than forcing users to wait around for a long-running delete operation would be to simply set an `Image.queuedForDeletion: true` flag, hide those images from the frontend to prevent users from seeing/interacting with them, and then perform the actual deletion with a scheduled cleanup job. This would also allow us to support "soft-deletion" or "archiving" of images so that users can change their mind and have the chance to move the images out of the trash for some amount of time.

- **async tasks**. I.e., the approach we have been taking with the async task Lambda.
