### ISSUE TITLE
Move `count` from `GetImages` payload to `GetStats`

### ISSUE THREAD

**Issue by nathanielrindlaub** [tnc-ca-geo/animl-api#160]
### Problem
We've discovered that counting all images that match a given aggregation pipeline is incredibly expensive and is now causing timeouts on `GetImages` queries. In our testing, getting the count took ~1000x longer than finding the paginated images themselves:

```javascript
  images: async (_, { input }, context) => {
    const count = await context.models.Image.countImages(input, context); // this often takes >10 seconds when querying projects with lots of images (>250k).
    const response = await context.models.Image.queryByFilter(input, context); // this typically takes less than 15ms
    const { previous, hasPrevious, next, hasNext, results } = response;
    return {
      pageInfo: {
        previous,
        hasPrevious,
        next,
        hasNext,
        count
      },
      images: results
    };
  },
```

Apparently this is a known inefficiency with MongoDB (see [this](https://stackoverflow.com/questions/9778420/mongo-count-really-slow-when-there-are-millions-of-records) and [this](https://www.dragonflydb.io/faq/mongodb-count-too-slow) for more info).

### Solution
Providing an accurate count of images that match a given set of filters is definitely a requirement, but as a compromise, we've decided to move the image `count` out of `GetImages` queries and into `GetStats`. The downside for the users is that they don't always get to see the matching image count displayed every time they change the filters, but they would still be able to access that information if they wanted to dig into the stats for their current selection.

### Tasks
- [ ] Remove `count` from `GetImages` payload
- [ ] Remove "matching images" display from frontend
- [ ] Build out better async task management (#159)
- [ ] Move `GetStats` function over to its own lambda, create a queue for it, and convert the `GetStats` graphql-api resolver to send an SQS message requesting `GetStats` which can be picked up and handled by the new Lambda
- [ ] Wire that up to the frontend and implement polling. 
- [ ] Style the stats modal (https://github.com/tnc-ca-geo/animl-frontend/issues/91)

**Comment by nathanielrindlaub** [comment]
FYI @ingalls and @jue-henry, I implemented what I hoped might be a temporary fix (https://github.com/tnc-ca-geo/animl-api/tree/image-count-temp-fix) in which we split out the query for `GetImagesCount` into it's own resolver, so the hope was if the count is independent of `GetImages`, even if the count times out, we can display that on the front end, but users can still view and filter their images (corresponding frontend branch is here: https://github.com/tnc-ca-geo/animl-frontend/tree/images-count-temp-fix).

This seems to work ok and as expected for most queries I've tried in prod thus far, except for trying to filter out (unselect) 'reviewed images' on the `sci_biosecurity` project. For that one, it's the `GetImages` query that is taking longer and timing out, not the `GetImagesCount`. Super odd...

@jue-henry that would be a good one to drill into in your indexing exploration.
