### ISSUE TITLE
Convert project to TypeScript

### ISSUE THREAD

**Issue by alukach** [tnc-ca-geo/animl-api#187]
### Core
- [x] Setup TypeScript tooling: #188
- [x] Convert Project glue code (config, db connect tooling, auth, errors, api handler): #189
- [x] Convert GraphQL TypeDefs: #195
  - Convert type-defs to GraphQL schema files
  - Setup automatic interface generation from GraphQL schema files
- [x] Convert DB Schemas: #205
- [x] Convert DB Models
  - `Batch.js` #208
  - `BatchError.js` #216
  - `Camera.js` #209
  - `Image.js` #224
  - `ImageError.ts` #211
  - `MLModel.js` #219
  - `Project.js`#220
  - `Task.js` #223
  - `User.js` #207
  - `colors.js` #210
  - `utils.js` #218
- [x] Convert GraphQL Resolvers: #229
- [x] Convert ML Handler: #232 
- [x] Convert Tasks: #233
